# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 567f3c141cffa2f0995cf6901da6229042c5e274ff7789a936515281842a373246d432f19a7844d5e9adee750adeee015f420b1bf0005729ea52ecae85736b2e

test:
  secret_key_base: ff4aef680eec47bcac4527afc2d4a612a3d44da544a12aabf7e27241b0bf36128ec0e21334ddb4711d9f0bb017ca35da03dab11ce65c96b68724efdf2bafa5d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
